# Generated by Django 5.1.1 on 2024-10-23 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('friendship', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='id_user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_set1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friends',
            name='id_user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_set2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='friends',
            constraint=models.UniqueConstraint(fields=('id_user1', 'id_user2'), name='unique_friendship'),
        ),
    ]
