# Generated by Django 5.1.1 on 2024-10-10 22:33

import publication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to=publication.models.blog_thumbnail_directory),
        ),
    ]
