# Generated by Django 5.1.1 on 2024-10-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='file_public_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.URLField(max_length=500),
        ),
    ]
